"""End-to-end data pipeline:  scrape -> clean -> convert -> store -> query.

    python run_pipeline.py            # full run against books.toscrape.com

Outputs (all regenerated from scratch on every run):
    data/books_raw.csv          raw scraped text, exactly as listed
    data/books_clean.csv        typed + converted columns
    zepto_books.db              SQLite database (categories + books, PK/FK)
    outputs/query_results.md    every SQL query string with its output,
                                pd.read_sql results, and the pd.merge comparison
The query results are also injected into README.md between the RESULTS markers.
"""
from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from cleaning import GBP_TO_INR, clean_books
from database import load_database
from queries import JOIN_QUERY, compare_join, merge_equivalent, read_sql_examples, run_queries
from scraper import CATEGORIES, scrape_books

HERE = Path(__file__).resolve().parent
DATA_DIR, OUT_DIR = HERE / "data", HERE / "outputs"
DB_PATH = HERE / "zepto_books.db"
README = HERE / "README.md"
START, END = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"

log = logging.getLogger("pipeline")


def md_table(df: pd.DataFrame, max_rows: int = 40) -> str:
    shown = df.head(max_rows)
    text = shown.to_markdown(index=False, floatfmt=".2f") if len(shown) else "_(query returned 0 rows)_"
    if len(df) > max_rows:
        text += f"\n\n_... {len(df) - max_rows} more rows not shown ({len(df)} total)_"
    return text


def build_report(raw, clean, report, results, read_sql_frames, merge_df, equal, side_by_side) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        f"_Generated by `python run_pipeline.py` on {ts}._\n",
        "### Run summary\n",
        f"- Scraped **{report['rows_scraped']}** books from **{report['categories']}** categories: "
        + ", ".join(f"{c} ({n})" for c, n in clean['category'].value_counts().sort_index().items()) + ".",
        f"- Rows dropped: missing title = {report['dropped_missing_title']}, "
        f"unparseable availability = {report['dropped_unparseable_availability']}.",
        f"- Median-imputed values: price_gbp = {report['imputed_price_gbp']}, rating = {report['imputed_rating']}.",
        f"- Clean rows loaded: **{report['rows_clean']}**. Conversion: price_inr = price_gbp x {GBP_TO_INR:.2f} "
        "(fixed project baseline, no API call).",
        "\n**Cleaned dtypes:** " + ", ".join(f"`{c}`: {t}" for c, t in clean.dtypes.astype(str).items()),
        "\n**Sample of cleaned rows:**\n",
        md_table(clean.head(5)),
        "\n### SQL queries and their output\n",
    ]
    for q, df in results:
        parts += [f"#### {q['name']}", f"Clauses demonstrated: {', '.join(q['clauses'])}  ",
                  f"Rows returned: {len(df)}\n", f"```sql{q['sql']}\n```\n", md_table(df), ""]
    parts.append("### `pd.read_sql` results\n")
    for name, df in read_sql_frames.items():
        parts += [f"**{name}** — `pd.read_sql(...)` -> DataFrame of shape {df.shape}\n", md_table(df, 15), ""]
    parts += [
        "### JOIN query (Q5) vs `pd.merge` — side by side\n",
        f"`pd.read_sql` shape: {read_sql_frames[JOIN_QUERY['name']].shape} · `pd.merge` shape: {merge_df.shape} · "
        f"`pd.testing.assert_frame_equal` passed · identical: **{equal}**\n",
        md_table(side_by_side, 40),
    ]
    return "\n".join(parts) + "\n"


def inject_into_readme(markdown: str) -> None:
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        README.write_text(f"{head}{START}\n{markdown}\n{END}{tail}", encoding="utf-8")
        log.info("README.md results section updated")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-readme", action="store_true", help="do not rewrite the README results section")
    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-7s %(message)s", datefmt="%H:%M:%S")

    DATA_DIR.mkdir(exist_ok=True); OUT_DIR.mkdir(exist_ok=True)

    log.info("1/5 scraping categories: %s", CATEGORIES)
    raw = pd.DataFrame(scrape_books(CATEGORIES))
    raw.to_csv(DATA_DIR / "books_raw.csv", index=False)

    log.info("2/5 cleaning + converting at 1 GBP = %.2f INR", GBP_TO_INR)
    clean, report = clean_books(raw)
    if report["rows_clean"] < 60 or report["categories"] < 3:
        log.error("Acceptance check failed: need >= 60 books across >= 3 categories, got %s / %s",
                  report["rows_clean"], report["categories"])
        return 1
    clean.to_csv(DATA_DIR / "books_clean.csv", index=False)

    log.info("3/5 loading SQLite database -> %s", DB_PATH.name)
    categories, books = load_database(clean, DB_PATH)

    log.info("4/5 running %d SQL queries", 7)
    results = run_queries(DB_PATH)
    for q, df in results:
        print(f"\n=== {q['name']} ({len(df)} rows) ===\n{q['sql'].strip()}\n{df.to_string(index=False)}")

    log.info("5/5 pd.read_sql + pd.merge equivalence")
    read_sql_frames = read_sql_examples(DB_PATH)
    merge_df = merge_equivalent(categories, books)
    equal, side = compare_join(read_sql_frames[JOIN_QUERY["name"]], merge_df)
    print("\n=== JOIN via pd.read_sql vs pd.merge (side by side) ===")
    print(side.to_string(index=False))
    print(f"\nIdentical: {equal}")

    markdown = build_report(raw, clean, report, results, read_sql_frames, merge_df, equal, side)
    (OUT_DIR / "query_results.md").write_text("# Query results\n\n" + markdown, encoding="utf-8")
    if not args.no_readme:
        inject_into_readme(markdown)
    log.info("done - see outputs/query_results.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
